service: some-booking-service

plugins:
  - serverless-plugin-modularize

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  timeout: 120
  region: ${opt:region, "us-east-1"}

custom:
  modularize:
    glob: "src/**/*.module.yml" # glob pattern
